pipeline {
    agent { node { label 'AGENT-1' } }
    options {
        ansiColor('xterm')
    }

    stages {
        stage('Init') {
            steps {
                sh'''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform init -reconfigure -lock=false
                '''
            }
        }
        stage('Plan') {
            steps {
                sh'''
                    ls -ltr
                    pwd
                    cd 01-vpc
                    terraform plan -lock=false
                '''
            }
        }
       
        stage('Apply') {
            steps{
                
                sh '''
                    pwd
                    ls -ltr
                    cd 01-vpc
                    terraform apply -auto-approve -lock=false
                '''
            }
        }
    }

    post { 
        always { 
            echo 'I will always run whether job is success or not'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when failure'
        }
    }
}
